### ISSUE TITLE
TFS2018 Support

### ISSUE THREAD

**Issue by bholbrook** [MicroFocus/octane-tfs-plugin#106]
Hi,

It doesn't look like this plugin currently supports TFS2018. Is this the case? Are there any plans to support it in the future?

**Comment by radislavB** [comment]
It’s in the roadmap.

**Comment by varunaiah** [comment]
We are also waiting for TFS2018 support, any update on this issue?

Thank you.

**Comment by radislavB** [comment]
Hi.
We are going to prioritize the TFS 2018.

**Comment by radislavB** [comment]
Hi.
In the nearest days we are starting to work on tfs 2018.
Generally we tested previous TFS 2017 with Maven and .Net Desktop build definitions.
Do you use additional build definitions templates in order to run tests?

Thanks

**Comment by varunaiah** [comment]
Hi,

We use [UFT TFS extension](https://marketplace.visualstudio.com/items?itemName=uftpublisher.application-UFT-TFS)

Thank you

**Comment by radislavB** [comment]
Hi.
Thank you for answer.
In order to add UFT support, I need more information
1.How do you store your tfs tests ? Locally, External Git repository, Tfs embedded git repository, ALM ? 
2.Is TFS your main CI server? are you using another CI servers, like Jenkins for example?
3.Can you send me screenshots of uft build definitions

If you want you can send it to my mail : radislav.berkovich@microfocus.com
Thank you.

**Comment by varunaiah** [comment]
hi,
TFS is our main CI Server
We are using TFS embedded Git for Visual Studio (C#, using Leanft & MsTests frameworks) to store our test scripts.
For UFT tests currently we are using Micro Focus ALM to store test scripts, object repo and function libraries. However, I would like to use TFS-Git to store UFT files and access them in ALM.net using [Micro Focus ALI Bundle](https://marketplace.microfocus.com/appdelivery/content/ali-bundle-0) , I think this will allow us to access TFS-GIT (I never tried before) and moreover the current version of ALI doesn’t support TFS2018 for ALM .Net version.
I will try to provide screenshots soon. 

Thank you

**Comment by radislavB** [comment]
published

**Comment by bholbrook** [comment]
Now that Azure DevOps Server 2019 has released, are there plans to start supporting that too?

**Comment by radislavB** [comment]
Hi.
Are you already using v2019?

**Comment by radislavB** [comment]
What kind of  build definitions templates you use in order to run tests?

**Comment by bholbrook** [comment]
Not just yet but we have plans in the next few weeks or so to upgrade.

We have a few a different build definition templates we use with varying steps included/modified. The main default templates would be **ASP.NET Core** and **ASP.NET**.
For .NET Core we use the **.NET Core** step with the **test** command.
For .NET we use **mstest** and **vstest**.

**Comment by radislavB** [comment]
Thanks for answer.
We just released plugin for tfs 2018 and waiting for customer inputs about plugin.  
Do you have plans to try plugin fot tfs 2018?

**Comment by bholbrook** [comment]
> Thanks for answer.
> We just released plugin for tfs 2018 and waiting for customer inputs about plugin.
> Do you have plans to try plugin fot tfs 2018?

Yes. We've actually just downloaded it today to start testing it.

**Comment by radislavB** [comment]
If you need help, don't hesitate to ask
