### ISSUE TITLE
Support for TFS2012

### ISSUE THREAD

**Issue by raka2407** [MicroFocus/octane-tfs-plugin#113]
Hi, can you please confirm if there is Octane plugin for TFS 2012 ? If no, are there any references to API services of Octane that can be consumed ? Thanks.

**Comment by radislavB** [comment]
We support currently tfs 2015 and tfs 2017.
About Apis - Do you search for some specific API?
You have available SDKs : https://admhelp.microfocus.com/octane/en/latest/Online/Content/API/articles_SDK.htm

Public Api : https://admhelp.microfocus.com/octane/en/latest/Online/Content/API/articles_API2.htm

**Comment by raka2407** [comment]
Thanks, can you please also comment on what an ER is, and how can it be added ?
