### ISSUE TITLE
Azure DevOps Services support (Cloud)

### ISSUE THREAD

**Issue by gitstua** [MicroFocus/octane-tfs-plugin#118]
Hi

I note a previous question about VSTS https://github.com/MicroFocus/octane-tfs-plugin/issues/104

Is there any plans to integrate the plugin with Azure DevOps Services or GitHub in future? I believe this would be useful for my large customer.

thanks - Stuart

**Comment by mayarfl** [comment]
Hi Stuart,

We have integration with Azure DevOps Services. Please take a look here:
[ALM Octane Integration with Azure DevOps Services](https://marketplace.visualstudio.com/items?itemName=ALMOctane.alm-octane-integration)

**Comment by gitstua** [comment]
Hi Maya, That link doesn't work for me - do I need to be added to the technical preview?
This is the message I get:
"We're sorry, the page you requested cannot be found!"

RE GitHub I was curious if you had any GitHub Actions support but the Azure DevOps link above should suffice if I can get access.

Thanks :)

**Comment by mayarfl** [comment]
Hi Stuart,

Actually the extension is private, so probably it is a problem to access the topic.
I can share share the extension with your organization, this way you will be able to reach also a topic and see how does work.

Thanks
Maya

**Comment by gitstua** [comment]
Can you share with my org dev.azure.com/stu-example-microfocus1 please?

**Comment by mayarfl** [comment]
Shared

**Comment by gitstua** [comment]
Thanks Maya
