### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by jdperaza** [MicroFocus/octane-tfs-plugin#88]
I'm trying to install the octane-tfs-plugin, but the installation fails.  Here are the details:
OS: Windows 10 Enterprise
TFS:
- Version: 2018
- Installed in: C:\Program Files\Microsoft Team Foundation Server 15.0
- It's a local, working installation of TFS.  I'm able to host a project on it, use it for versioning source code (using Git), and connect my Visual Studio to it.  From my Visual Studio, I'm able to make a source-code change, commit-push the change, and it triggers an automatic build in TFS.  So my TFS installation seems to be stable and working.

Here's the error I get, when I execute setup.exe to install the plugin.  See the attached dialog.
![installfail](https://user-images.githubusercontent.com/37339993/37349677-f69f79b8-26a4-11e8-9714-21c1bb62843a.PNG)

I've even tried running the setup as Administrator, but I get the same error.

**Comment by jdperaza** [comment]
Hello, just wondering how the support process works for this plugin.  Will anyone be assigned to review my issue?

**Comment by m-seldin** [comment]
@jdperaza 
hi , TFS 2018 is currently unsupported by the plugin.
